[Settings]
input_folder      = photos_a_traiter
output_folder     = photos_traitees

target_square_size = 2000
object_fill_ratio  = 0.78

model_name         = isnet-general-use
sort_order         = natural

padding_threshold  = 20

# True = bords fins, False = masque brut (ombres mieux conservées)
use_alpha_matting  = True

alpha_fg_threshold = 200
alpha_bg_threshold = 30
alpha_erode_size   = 6
